version: '3.8'

services:
  app:
    image: gustavenrique/symfony-app
    container_name: symfony-app
    restart: always
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./ui:/var/www
      - /var/www/vendor
      - /var/www/node_modules

  db:
    image: mysql:8.1
    container_name: symfony-db
    restart: always
    env_file:
      - ./db/.env
    volumes:
      - ./db/mysql:/var/lib/mysql
    ports:
      - 3306:3306
#   ###> symfony/mailer ###
#   mailer:
#     image: schickling/mailcatcher
#     ports: ['1025', '1080']
#   ###< symfony/mailer ###

# volumes:
#   ###> doctrine/doctrine-bundle ###
#   database_data:
#   ###< doctrine/doctrine-bundle ###
