webpack_encore:
    output_path: "%kernel.project_dir%/public/build"

    # Set attributes that will be rendered on all script and link tags
    script_attributes:
        defer: true

    # If using Encore.enableIntegrityHashes() and need the crossorigin attribute (default: false, or use 'anonymous' or 'use-credentials')
    # crossorigin: 'anonymous'

    # Preload all rendered script and link tags automatically via the HTTP/2 Link header
    # preload: true

framework:
    assets:
        json_manifest_path: "%kernel.project_dir%/public/build/manifest.json"
#when@prod:
#    webpack_encore:
#        # Cache the entrypoints.json (rebuild Symfony's cache when entrypoints.json changes)
#        # Available in version 1.2
#        cache: true

#when@test:
#    webpack_encore:
#        strict_mode: false
